version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16
    container_name: tipicos-db
    environment:
      POSTGRES_DB: tipicos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./tipicos_tpi135_2025.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servidor Open Liberty
  app:
    build: .
    container_name: tipicos-app
    ports:
      - 9080:9080
      - 9443:9443
    environment:
      - DB_SERVER=postgres
      - DB_PORT=5432
      - DB_NAME=tipicos
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
