version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:14
    container_name: tipicos-db
    environment:
      POSTGRES_DB: tipicos_tpi135
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./tipicos_tpi135_2025.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tipicos-network

  # Servidor de aplicaciones (GlassFish/Payara)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tipicos-app
    ports:
      - "9080:8080"  # Puerto HTTP
      - "4848:4848"  # Puerto Admin
      - "8181:8181"  # Puerto HTTPS
    environment:
      - DB_SERVER=postgres
      - DB_PORT=5432
      - DB_NAME=tipicos_tpi135
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tipicos-network
    volumes:
      - ./target/tipicos-api.war:/opt/payara/deployments/tipicos-api.war

networks:
  tipicos-network:
    driver: bridge

volumes:
  postgres-data:
