services:
  # Base de datos PostgreSQL para pruebas
  postgres-test:
    image: postgres:14
    container_name: tipicos-db-test
    environment:
      POSTGRES_DB: tipicos_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tipicos-test-network

  # Aplicación GlassFish para pruebas
  tipicos-app-test:
    build: .
    container_name: tipicos-app-test
    depends_on:
      postgres-test:
        condition: service_healthy
    ports:
      - 8080:8080
      - 4848:4848
      - 8181:8181
    environment:
      - DB_SERVER=postgres-test
      - DB_PORT=5432
      - DB_NAME=tipicos_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - tipicos-test-network

networks:
  tipicos-test-network:
    driver: bridge
version: '3.8'

services:
  # Base de datos PostgreSQL para pruebas
  postgres-test:
    image: postgres:14
    container_name: tipicos-db-test
    environment:
      POSTGRES_DB: tipicos_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tipicos-test-network

  # Aplicación para pruebas
  tipicos-app-test:
    build: .
    container_name: tipicos-app-test
    depends_on:
      postgres-test:
        condition: service_healthy
    ports:
      - 8080:8080
      - 4848:4848
      - 8181:8181
    environment:
      - DB_SERVER=postgres-test
      - DB_PORT=5432
      - DB_NAME=tipicos_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - tipicos-test-network

networks:
  tipicos-test-network:
    driver: bridge
