version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:14
    container_name: tipicos-db
    environment:
      POSTGRES_DB: tipicos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tipicos-network

  # Aplicación OpenLiberty
  tipicos-app:
    build: .
    container_name: tipicos-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9080:9080"
      - "9443:9443"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tipicos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - tipicos-network

volumes:
  postgres-data:

networks:
  tipicos-network:
    driver: bridge
